---
- hosts: localhost
  gather_facts: no
  vars:
    package_name: ntpd
  tasks:
  - debug:
      msg: "{{ package_name }}"
  - name: Update and install required packages
    ansible.builtin.dnf:
      name: "{{ package_name }}"
      state: latest
      update_cache: yes
  - debug:
      msg: "On {{ inventory_hostname }} machine, following packages have been installed/updated {{ package_name }}"

