---
- hosts: Rhel_Servers
  gather_facts: no
  tasks:
    - name: check if reboot is required
      shell: needs-restarting -r
      failed_when: false
      register: reboot_required
      changed_when: false
    - name: display package count
      debug:
        msg: "{ updates.stdout }}"
    - name: display package count
      debug:
        msg: "{ reboot_required }}"
