---
- hosts: Rhel_Servers
  gather_facts: no
  tasks:
    - name: packages to update
      shell: yum list updates | awk 'f;/Updated Packages/{f=1;}' | awk '{ print $1 }'
      changed_when: updates.stdout_lines | length > 0
      args:
        warn: false
      register: updates
 #   - name: display package count
 #     debug:
 #       msg: "Found {{ updates.stdout_lines | length }} packages that needs updating:\n\n{{ updates.stdout }}"
    - name: display package count
      debug:
        msg: "{ updates.stdout }}"
